import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getDatabase,ref,push,set,update,remove,onValue,serverTimestamp,query,limitToLast}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
const firebaseConfig={apiKey:"AIzaSyA4aHl9xv_v3fFPfgQ10-T_ifJ00Frni8Y",authDomain:"main-128f7.firebaseapp.com",databaseURL:"https://main-128f7-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"main-128f7",storageBucket:"main-128f7.firebasestorage.app",messagingSenderId:"50099445496",appId:"1:50099445496:web:382017fc1daea3ec86a50d",measurementId:"G-6ET6VBK9L0"};const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),$=x=>document.getElementById(x);let user=null,accounts={},privacy=localStorage.getItem("agenticPrivacy")==="true";
const esc=s=>{let d=document.createElement("div");d.textContent=s||"";return d.innerHTML},fmt=v=>new Intl.DateTimeFormat("en-PH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
function reset(a){let d=new Date(a.limitDate),p=a.period||"week";if(p==="month")d.setMonth(d.getMonth()+1);else if(p==="custom"){let v=Number(a.customValue)||1,u=a.customUnit||"days";if(u==="months")d.setMonth(d.getMonth()+v);else d.setDate(d.getDate()+v*(u==="weeks"?7:1))}else d.setDate(d.getDate()+7);return d.getTime()}
function localDT(d=new Date()){let p=n=>String(n).padStart(2,"0");return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function countdown(ms){if(ms<=0)return"Available";let s=Math.floor(ms/1e3),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return[d?`${d}d`:"",h?`${h}h`:"",`${m}m`].filter(Boolean).join(" ")}
function periodLabel(a){if((a.period||"week")==="month")return"1 month";if(a.period==="custom")return`${a.customValue} ${a.customUnit}`;return"1 week"}
function applyPrivacy(){document.querySelectorAll(".email").forEach(x=>x.classList.toggle("privacy-blur",privacy));$("user").classList.toggle("privacy-blur",privacy);$("activitySection").classList.toggle("is-hidden",privacy);$("privacy").textContent=privacy?"◉":"◎";$("privacy").title=privacy?"Show private information":"Hide private information";localStorage.setItem("agenticPrivacy",privacy)}
function refreshAppFilter(){let s=$("appFilter"),current=s.value,names=[...new Set(Object.values(accounts).map(a=>(a.agenticName||"Unspecified").trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));s.innerHTML='<option value="all">All agentic apps</option>'+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join("");if(names.includes(current))s.value=current}
function render(){let n=Date.now(),all=Object.entries(accounts).sort((a,b)=>reset(a[1])-reset(b[1])),totalReady=all.filter(([,a])=>n>=reset(a)).length,q=($("search")?.value||"").toLowerCase().trim(),sf=$("statusFilter")?.value||"all",af=$("appFilter")?.value||"all";let e=all.filter(([,a])=>{let ok=n>=reset(a),service=a.agenticName||"Unspecified";return(!q||a.email.toLowerCase().includes(q)||service.toLowerCase().includes(q))&&(sf==="all"||(sf==="ready"&&ok)||(sf==="cooldown"&&!ok))&&(af==="all"||service===af)});$("list").innerHTML=e.length?e.map(([id,a])=>{let t=reset(a),ok=n>=t;return`<article class="card"><div class="identity"><div class="email">${esc(a.email)}</div><span class="service">${esc(a.agenticName||"Unspecified")}</span><span class="meta">${periodLabel(a)}</span></div><div class="usage"><div class="count">${countdown(t-n)} <span class="badge ${ok?"ok":"wait"}">${ok?"READY":"COOLDOWN"}</span></div><div class="resetText">Reset: ${fmt(t)}</div></div><div class="cardActions"><button class="used" data-used="${id}">Used</button><button class="secondary" data-edit="${id}">Edit</button><button class="danger" data-delete="${id}">Delete</button></div></article>`}).join(""):`<div class="emptyFiltered">No accounts match your search or filters.</div>`;$("total").textContent=all.length;$("ready").textContent=totalReady;$("waiting").textContent=all.length-totalReady;$("filterCount").textContent=e.length===all.length?"":`Showing ${e.length} of ${all.length} accounts`;applyPrivacy()}
async function log(m){if(user)await set(push(ref(db,`users/${user.uid}/activity`)),{message:m,timestamp:serverTimestamp()})}
onAuthStateChanged(auth,u=>{user=u;$("auth").classList.toggle("is-hidden",!!u);$("dashboard").classList.toggle("is-hidden",!u);if(u){$("user").textContent=`Signed in as ${u.email}`;onValue(ref(db,`users/${u.uid}/accounts`),s=>{accounts=s.val()||{};refreshAppFilter();render()});onValue(query(ref(db,`users/${u.uid}/activity`),limitToLast(20)),s=>{let a=Object.values(s.val()||{}).sort((x,y)=>(y.timestamp||0)-(x.timestamp||0));$("activity").innerHTML=a.map(x=>`<div class="activity-item">${esc(x.message)} · ${x.timestamp?fmt(x.timestamp):"Just now"}</div>`).join("");applyPrivacy()})}});
$("loginForm").onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$("loginEmail").value,$("loginPassword").value)}catch(x){$("msg").textContent="Sign in failed."}};$("register").onclick=()=>createUserWithEmailAndPassword(auth,$("loginEmail").value,$("loginPassword").value);$("logout").onclick=()=>signOut(auth);$("privacy").onclick=()=>{privacy=!privacy;applyPrivacy()};
function openAdd(){$("accountForm").reset();$("editId").value="";$("limitDate").value=localDT();$("period").value="week";$("customWrap").classList.add("is-hidden");$("modalTitle").textContent="Add Account";$("modal").showModal()}$("add").onclick=openAdd;$("cancel").onclick=$("x").onclick=()=>$("modal").close();$("period").onchange=()=>$("customWrap").classList.toggle("is-hidden",$("period").value!=="custom");
$("list").onclick=async e=>{let id=e.target.dataset.used;if(id){let a=accounts[id];await update(ref(db,`users/${user.uid}/accounts/${id}`),{limitDate:localDT(),updatedAt:serverTimestamp()});await log(`Marked ${a.email} (${a.agenticName||"Unspecified"}) as fully used.`);return}id=e.target.dataset.edit;if(id){let a=accounts[id];$("editId").value=id;$("email").value=a.email;$("agenticName").value=a.agenticName||"";$("limitDate").value=a.limitDate;$("period").value=a.period||"week";$("customValue").value=a.customValue||1;$("customUnit").value=a.customUnit||"days";$("customWrap").classList.toggle("is-hidden",$("period").value!=="custom");$("modalTitle").textContent="Edit Account";$("modal").showModal();return}id=e.target.dataset.delete;if(id&&confirm("Delete this account?"))await remove(ref(db,`users/${user.uid}/accounts/${id}`))};
$("accountForm").onsubmit=async e=>{e.preventDefault();let id=$("editId").value,data={email:$("email").value.trim(),agenticName:$("agenticName").value.trim(),limitDate:$("limitDate").value,period:$("period").value,customValue:Number($("customValue").value)||1,customUnit:$("customUnit").value,updatedAt:serverTimestamp()};if(id)await update(ref(db,`users/${user.uid}/accounts/${id}`),data);else{data.createdAt=serverTimestamp();await set(push(ref(db,`users/${user.uid}/accounts`)),data)}await log(`${id?"Updated":"Added"} ${data.email} (${data.agenticName}).`);$("modal").close()};
$("search").addEventListener("input",render);$("statusFilter").addEventListener("change",render);$("appFilter").addEventListener("change",render);function theme(t){document.documentElement.dataset.theme=t;localStorage.setItem("agenticTheme",t);$("theme").textContent=t==="dark"?"☀":"☾"}theme(localStorage.getItem("agenticTheme")||"light");$("theme").onclick=()=>theme(document.documentElement.dataset.theme==="dark"?"light":"dark");setInterval(()=>user&&render(),30000);