import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getDatabase,ref,push,set,update,remove,onValue,serverTimestamp,query,limitToLast}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
const firebaseConfig={apiKey:"AIzaSyA4aHl9xv_v3fFPfgQ10-T_ifJ00Frni8Y",authDomain:"main-128f7.firebaseapp.com",databaseURL:"https://main-128f7-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"main-128f7",storageBucket:"main-128f7.firebasestorage.app",messagingSenderId:"50099445496",appId:"1:50099445496:web:382017fc1daea3ec86a50d",measurementId:"G-6ET6VBK9L0"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),$=x=>document.getElementById(x);let user=null,accounts={},unsubA=null,unsubL=null;
const esc=s=>{let d=document.createElement("div");d.textContent=s||"";return d.innerHTML},fmt=v=>new Intl.DateTimeFormat("en-PH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)),reset=a=>new Date(a.limitDate).getTime()+a.resetDays*864e5;
function localDT(d=new Date()){let p=n=>String(n).padStart(2,"0");return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function countdown(ms){if(ms<=0)return"Available";let s=Math.floor(ms/1e3);return`${Math.floor(s/86400)}d ${Math.floor(s%86400/3600)}h ${Math.floor(s%3600/60)}m`}
function showView(signedIn){$("auth").classList.toggle("is-hidden",signedIn);$("dashboard").classList.toggle("is-hidden",!signedIn)}
function render(){let n=Date.now(),r=0,e=Object.entries(accounts).sort((a,b)=>reset(a[1])-reset(b[1]));$("list").innerHTML=e.map(([id,a])=>{let t=reset(a),ok=n>=t;if(ok)r++;let service=a.agenticName||"Unspecified";return`<article class="card"><div class="identity"><div class="email">${esc(a.email)}</div><span class="service">${esc(service)}</span><span class="meta">Used ${fmt(a.limitDate)}</span></div><div class="usage"><div class="count">${countdown(t-n)} <span class="badge ${ok?"ok":"wait"}">${ok?"READY":"COOLDOWN"}</span></div><div class="resetText">Reset: ${fmt(t)}</div></div><div class="cardActions"><button class="used" data-used="${id}">Used</button><button class="secondary" data-edit="${id}">Edit</button><button class="danger" data-delete="${id}">Delete</button></div></article>`}).join("");$("total").textContent=e.length;$("ready").textContent=r;$("waiting").textContent=e.length-r}
async function log(message){if(user)await set(push(ref(db,`users/${user.uid}/activity`)),{message,timestamp:serverTimestamp()})}
onAuthStateChanged(auth,u=>{user=u;showView(!!u);if(unsubA){unsubA();unsubA=null}if(unsubL){unsubL();unsubL=null}if(u){$("user").textContent=`Signed in as ${u.email}`;unsubA=onValue(ref(db,`users/${u.uid}/accounts`),s=>{accounts=s.val()||{};render()});unsubL=onValue(query(ref(db,`users/${u.uid}/activity`),limitToLast(20)),s=>{let a=Object.values(s.val()||{}).sort((x,y)=>(y.timestamp||0)-(x.timestamp||0));$("activity").innerHTML=a.length?a.map(x=>`<div class="activity-item">${esc(x.message)} · ${x.timestamp?fmt(x.timestamp):"Just now"}</div>`).join(""):`<p class="activity-item">No activity yet.</p>`})}else accounts={}});
$("loginForm").onsubmit=async e=>{e.preventDefault();$("msg").textContent="";try{await signInWithEmailAndPassword(auth,$("loginEmail").value,$("loginPassword").value)}catch(x){$("msg").textContent="Sign in failed. Check your email and password."}};$("register").onclick=async()=>{try{let c=await createUserWithEmailAndPassword(auth,$("loginEmail").value,$("loginPassword").value);user=c.user;await log("Account created.")}catch(x){$("msg").textContent=x.message}};$("logout").onclick=()=>signOut(auth);
function openAdd(){$("accountForm").reset();$("editId").value="";$("limitDate").value=localDT();$("days").value="7";$("modalTitle").textContent="Add Account";$("modal").showModal()}$("add").onclick=openAdd;$("cancel").onclick=$("x").onclick=()=>$("modal").close();
$("list").onclick=async e=>{let id=e.target.dataset.used;if(id){let a=accounts[id],now=localDT();await update(ref(db,`users/${user.uid}/accounts/${id}`),{limitDate:now,updatedAt:serverTimestamp()});await log(`Marked ${a.email} (${a.agenticName||"Unspecified"}) as fully used.`);return}id=e.target.dataset.edit;if(id){let a=accounts[id];$("editId").value=id;$("email").value=a.email;$("agenticName").value=a.agenticName||"";$("limitDate").value=a.limitDate;$("days").value=a.resetDays;$("modalTitle").textContent="Edit Account";$("modal").showModal();return}id=e.target.dataset.delete;if(id&&confirm("Delete this account?")){let a=accounts[id];await remove(ref(db,`users/${user.uid}/accounts/${id}`));await log(`Deleted ${a.email} (${a.agenticName||"Unspecified"}).`)}};
$("accountForm").onsubmit=async e=>{e.preventDefault();let id=$("editId").value,data={email:$("email").value.trim(),agenticName:$("agenticName").value.trim(),limitDate:$("limitDate").value,resetDays:Number($("days").value),updatedAt:serverTimestamp()};if(id){await update(ref(db,`users/${user.uid}/accounts/${id}`),data);await log(`Updated ${data.email} (${data.agenticName}).`)}else{data.createdAt=serverTimestamp();await set(push(ref(db,`users/${user.uid}/accounts`)),data);await log(`Added ${data.email} (${data.agenticName}).`)}$("modal").close()};
function theme(t){document.documentElement.dataset.theme=t;localStorage.setItem("agenticTheme",t);$("theme").textContent=t==="dark"?"☀":"☾"}theme(localStorage.getItem("agenticTheme")||"light");$("theme").onclick=()=>theme(document.documentElement.dataset.theme==="dark"?"light":"dark");setInterval(()=>user&&render(),30000);